service:
  name: hexagonal-lambda

plugins:
  - serverless-webpack

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectAcl
      Resource: "arn:aws:s3:::${self:custom.finalBillBucketName}/*"

custom:
  finalBillBucketName: final-bill-bucket-${self:provider.stage}

functions:
  closeAccountHttp:
    handler: handlerHttp.handler
    events:
      - http:
          method: DELETE
          path: account/{id}
          request:
            parameters:
              paths:
                id: true
  closeAccountS3:
    handler: handlerS3.handler
    events:
      - s3: ${self:custom.finalBillBucketName}
        event: s3:ObjectCreated:*

resources:
  Resources:
    FinalBillBucketLambdaPermission:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - CloseAccountS3LambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::${self:custom.finalBillBucketName}"
