service:
  name: hexagonal-lambda

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10

custom:
  serverless-offline:
    port: 8080

functions:
  closeAccountHttp:
    handler: handlerHttp.handler
    events:
      - http:
          method: DELETE
          path: account/{id}
          request:
            parameters:
              paths:
                id: true
  closeAccountS3:
    handler: handlerS3.handler
    events:
      - s3: final-statement-bucket
        event: s3:*

resources:
  Resources:
    FinalStatementBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: final-statement-bucket
